---
title: Energy Markets Analysis
author: Bryce Lim
date: Start date 01/06/23
output:
  html_document:
    toc: true
    toc_depth: 2
    toc_float:
      collapsed: false
      smooth_scroll: false
---


```{r setup, warning = FALSE, message=FALSE}
### Load Libraries ###
library(yaml)
library(tidyverse)
library(lubridate)
library(data.table)
library(plotly)

### Load config ###
config <- yaml::yaml.load_file("Config.yml")
```

```{r Load data}
### Load the raw data ###
RT_OTA_BEN <- fread(config$data$OTA_BEN)
```


## Monthly Nationally Spot Price

```{r Analysis}
# Wrangle the data - change date into lubridate and add year month
WT_OTA_BEN <- RT_OTA_BEN

WT_OTA_BEN[, TradingDate := ymd(TradingDate)]
WT_OTA_BEN[, c("Year","Month") := list(lubridate::year(TradingDate),lubridate::month(TradingDate))]
WT_OTA_BEN[, YearMonth := paste(Year,str_pad(Month, 2, pad="0"),sep ='-')]

# Summarise price and order data
WT_OTA_BEN_Daily <- WT_OTA_BEN[, .(Price = mean(DollarsPerMegawattHour)), by= .(TradingDate,PointOfConnection)]
WT_OTA_BEN_Daily <- WT_OTA_BEN_Daily[order(TradingDate)]

# Get monthly data
WT_OTA_BEN_Monthly <- WT_OTA_BEN[, .(Price = mean(DollarsPerMegawattHour)), by= .(YearMonth,PointOfConnection)]
WT_OTA_BEN_Monthly <- WT_OTA_BEN_Monthly[order(YearMonth)]

# plot the monthly data
FP_OTA_BEN_Monthly <- WT_OTA_BEN_Monthly %>% plot_ly(
  x = ~ YearMonth,
  y = ~ Price,
  # name = '',
  type = 'scatter',
  mode = 'line',
  color = ~PointOfConnection,
  colors = c("deepskyblue", "darkorange")
)
FP_OTA_BEN_Monthly <- FP_OTA_BEN_Monthly %>% rangeslider() %>%
layout(
    title = "Monthly Spot Price at Otahuhu and Benmore (2010 - Present)",
    xaxis = list(title = "Year and Month"),
    yaxis = list(title = "Price"))
    
FP_OTA_BEN_Monthly
```

<div class="tocify-extend-page" data-unique="tocify-extend-page" style="height: 0;"></div>

